### PR TITLE
Use system kindlegen when available; Add VERSION constant

### PR DESCRIPTION
**Pull request by bianjp**
* Use system installed kindlegen when available
* Add `Kindlerb::VERSION` constant for users to check version
* Add `Kindlerb.kindlegen_available?` method for users to check whether Kindlerb can work
* Rename `executable` local variable to `executable_filename` to avoid possible ambiguity with `executable` class method

Please release a new version as soon as possible if you accepted this PR.

### CODE REVIEW

**Comment by danchoi** [comment]
Thank you. Do you want to be added to gem maintainers?

**Comment by bianjp** [comment]
Yeah. Though I'm not very interested in it, it seems quite simple, and I should be able to spare some time for it.

**Comment by emiraydin** [comment]
@danchoi @bianjp please bump up the version one major up. Renaming `executable` to `executable_filename` is a breaking change.

**Comment by danchoi** [comment]
Thank you Emir. I pushed the version change and the new gem version

**Comment by bianjp** [comment]
In fact there is no breaking change...

**Comment by emiraydin** [comment]
@bianjp yes I noticed right after writing so I deleted the comment. I thought you changed the `executable` method not the local variable. Still though, you added a new method `kindlegen_available?`, so this requires a minor version bump. 1.1.0 I would say.

**Pull request merged**
